apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c', 
          'until pg_isready -h db -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: backend
        image: nigelpoulton/ckad:pluralsight_backend
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: db-access
        env:
        - name: PGPASSWORD
          value: k8srocks
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(PGPASSWORD)@db:5432/$(POSTGRES_DB)"
        readinessProbe:
          httpGet:
            path: /api/v1/
            port: api
        livenessProbe:
          httpGet:
            path: /api/v1/
            port: api
        ports:
          - name: api
            containerPort: 8000
