apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ckad
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: a17d0c8b8c28b4c76a47debb8b4e472e-1231363517.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: a17d0c8b8c28b4c76a47debb8b4e472e-1231363517.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
  - host: a17d0c8b8c28b4c76a47debb8b4e472e-1231363517.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80